{
 "title": "ECE Overview",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ece_allocator_info,common_cluster_name)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(ece_allocator_info{common_cluster_name=~\"$cluster\"},zone)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Allocators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_allocator_info{common_cluster_name=~\"$cluster\",healthy=\"true\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Allocators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_allocator_info{common_cluster_name=~\"$cluster\",healthy!=\"true\"}) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disconnected Allocators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_allocator_info{common_cluster_name=~\"$cluster\",connected!=\"true\"}) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Proxies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_proxy_info{common_cluster_name=~\"$cluster\",healthy=\"false\"}) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocator RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_allocator_memory_used) / sum(ece_allocator_memory_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elastic Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (name) (sum by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\",zone=~\"$zone\"})))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Elastic Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\",zone=~\"$zone\",healthy!=\"true\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elastic Pending Plans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (ece_allocator_instance_plan{common_cluster_name=~\"$cluster\",zone=~\"$zone\",pending=\"true\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Allocators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Healthy Allocators per Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone,common_cluster_name) (ece_allocator_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", healthy=\"true\"})",
     "legendFormat": "{{common_cluster_name}} {{zone}}"
    }
   ]
  },
  {
   "title": "Cluster Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (common_cluster_name) (ece_allocator_memory_used{common_cluster_name=~\"$cluster\", zone=~\"$zone\"}) / sum by (common_cluster_name) (ece_allocator_memory_total{common_cluster_name=~\"$cluster\", zone=~\"$zone\"})",
     "legendFormat": "{{common_cluster_name }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Cluster Zone Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (common_cluster_name, zone) (ece_allocator_memory_used{common_cluster_name=~\"$cluster\", zone=~\"$zone\"}) / sum by (common_cluster_name, zone) (ece_allocator_memory_total{common_cluster_name=~\"$cluster\", zone=~\"$zone\"})",
     "legendFormat": "{{common_cluster_name }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Healthy Proxies per Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone,common_cluster_name) (ece_proxy_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", healthy=\"true\"})",
     "legendFormat": "{{common_cluster_name}} {{zone}}"
    }
   ]
  },
  {
   "title": "Host Memory Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ece_allocator_memory_used{common_cluster_name=~\"$cluster\", zone=~\"$zone\"} / ece_allocator_memory_total{common_cluster_name=~\"$cluster\", zone=~\"$zone\"}",
     "legendFormat": "{{common_cluster_name }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Zone Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (zone, common_cluster_name) (ece_allocator_memory_used{common_cluster_name=~\"$cluster\", zone=~\"$zone\"})",
     "legendFormat": "{{ common_cluster_name }} {{ zone }}: used"
    },
    {
     "expr": "sum by (zone, common_cluster_name) (ece_allocator_memory_total{common_cluster_name=~\"$cluster\", zone=~\"$zone\"} - ece_allocator_memory_used{common_cluster_name=~\"$cluster\", zone=~\"$zone\"})",
     "legendFormat": "{{ common_cluster_name }} {{ zone }}: available"
    }
   ]
  },
  {
   "title": "ElasticSearch Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastic Cluster Total Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_node_memory{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_type=\"elasticsearch\", name=~\"$instance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Kibana Total Size per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_node_memory{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_type=\"kibana\", name=~\"$instance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Elastic Cluster Moving",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", moving=\"true\", name=~\"$instance\"}) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Elastic Cluster Average Node Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_node_memory{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_type=\"elasticsearch\", name=~\"$instance\"}) / count by (name) (ece_allocator_instance_node_memory{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_type=\"elasticsearch\", name=~\"$instance\"}) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Elastic Cluster Unhealthy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (name) (count by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_healthy=\"false\", name=~\"$instance\"})) > 0",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Elastic Clusters with Pending Plans",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (zone,name,common_cluster_name) (sum by (zone,name,common_cluster_name) (ece_allocator_instance_plan{common_cluster_name=~\"$cluster\", zone=~\"$zone\", pending=\"true\", name=~\"$instance\"}))",
       "legendFormat": "{{common_cluster_name}} {{zone}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastic Cluster Container Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", cluster_type=\"elasticsearch\", name=~\"$instance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Elastic Containers Unhealthy per Zone",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (zone,common_cluster_name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", healthy=\"false\", name=~\"$instance\"})",
       "legendFormat": "{{common_cluster_name}} {{zone}}"
      }
     ]
    },
    {
     "title": "Elastic Containers Unhealthy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (ece_allocator_instance_info{common_cluster_name=~\"$cluster\", zone=~\"$zone\", healthy=\"false\", name=~\"$instance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers Deployed per Zone",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (zone, common_cluster_name) (ece_allocator_instances_total{common_cluster_name=~\"$cluster\", zone=~\"$zone\"})",
       "legendFormat": "{{ common_cluster_name }} {{ zone }}"
      }
     ]
    }
   ]
  }
 ]
}